### Get all guests
GET http://localhost:3000/api/v1/guests

### Get all guests
GET http://localhost:9000/api/v1/guests/pageable?size=7&page=5&sort=idGuest,desc

### Get all guests
GET http://localhost:9000/api/v1/guests/pageable

### Get all guests
GET http://localhost:9000/api/v1/guests/pageableNotDefault?size=7&page=5

### Get all guests
GET http://localhost:4000/api/v1/guests/sorted?field=firstName

### Create a guests
POST http://localhost:9000/api/v1/guests
Content-Type: application/json 

{
"firstName": "Manuel",
"last_name": "Arias",
"birthDay": "120819s85",
"nationality":"Colombiano",
"phone":"311144555",
"reservationsDto": [
    {
      "dateIn" : "2May",
      "dateOut": "8May",
      "payUsed":"CreditCard",
      "costToPay": "100"
    },
    {
      "dateIn" : "5August",
      "dateOut": "25August",
      "payUsed":"CreditCard",
      "costToPay": "100"

    }
  ]
}

### Update a guests
PUT http://localhost:4000/api/v1/guests/edit/3
Content-Type: application/json 

{
"firstName": "Manuel updated",
"last_name": "Arias updated",
"birthDay": "01011985",
"nationality":"Colombiano updated",
"phone":"311144555 updated",
"reservationsDto": [
    {
      "id": 4,
      "dateIn" : "5August Update",
      "dateOut": "5August Updated",
      "payUsed":"CreditCard Updated",
      "costToPay": "200"
    }
  ]
}

### Delete a guests
DELETE http://localhost:4000/api/v1/guests/delete/2
