server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hotel-mysql?createDatabaseIfNotExist=true
    username: root
    password: manuelpass
  jpa:
    hibernate:
      ddl-auto: create-drop
