server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hotel-postgres
    username: postgres
    password: manuelpass
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
